language:       ocaml
before_install: sudo apt-get update -qq
install:        sudo apt-get install -y ocaml ocaml-nox ocaml-native-compilers camlp4-extra time libgtk2.0 libgtksourceview2.0
env:
  - PACKAGE=Foundations
  - PACKAGE=CategoryTheory
  - PACKAGE=Ktheory
  - PACKAGE=Dedekind
  - PACKAGE=SubstitutionSystems
  - PACKAGE=Tactics
script:
  - time make BUILD_COQIDE=yes build-coq
  - time make TIMECMD=time $PACKAGE
