# validate this file at http://lint.travis-ci.org/
# ocaml and coq are not on the list of languages:
language:       generic
sudo: 		required
# "trusty" is the most modern release of Ubuntu supported
dist: 		trusty
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y ocaml ocaml-nox ocaml-native-compilers
  - sudo apt-get install -y camlp5 camlp4-extra time libgtk2.0 libgtksourceview2.0
# build coqide along with the Tactics package, just because it's a short package
env:
  - PACKAGE=Foundations
  - PACKAGE=CategoryTheory
  - PACKAGE=Ktheory
  - PACKAGE=Topology
  - PACKAGE=RealNumbers
  - PACKAGE=SubstitutionSystems
  - PACKAGE=Tactics BUILD_COQIDE=yes
  - PACKAGE=Folds
# building Coq in a separate stage folds up the output in the log:
before_script:
  - time make build-coq
script:
  - time make TIMECMD=time $PACKAGE
