# This is a basic workflow to help you get started with Actions

name: CI-Build-Satellites

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      # Install everything needed for building UniMath (and more)
      - name: Install build dependencies
        run: |
	  sudo apt-get update
	  sudo apt-get install build-essential git ocaml ocaml-nox ocaml-native-compilers camlp5 libgtk2.0 libgtksourceview2.0 liblablgtk-extras-ocaml-dev ocaml-findlib libnum-ocaml-dev emacs

      # Change into UniMath directory and build UniMath
      - name: Build UniMath and libraries TypeTheory, Largecatmodules, and SetHITs
        run: |
          pushd $GITHUB_WORKSPACE
          make build-coq
          make -j2
          make install
          export PATH=$PATH:$PWD/sub/coq/bin/
          echo $PATH
          popd
          # build TypeTheory
          git clone https://github.com/UniMath/TypeTheory
          pushd TypeTheory
          make
          popd
          # build largecatmodules
          git clone https://github.com/UniMath/largecatmodules
          pushd largecatmodules
          make
          popd
          # build SetHITS
          git clone https://github.com/UniMath/SetHITs
          pushd SetHITs
          cd code
          coq_makefile -f _CoqProject -o Makefile
          make
          popd
